# Generated by Django 2.2.3 on 2019-08-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_post',
            new_name='text',
        ),
    ]
