# Generated by Django 2.2.4 on 2019-08-11 13:21

import blogengine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(default='', editable=False, upload_to=blogengine.models.generate_path_image_thumbnail),
            preserve_default=False,
        ),
    ]
