# Generated by Django 2.2.4 on 2019-08-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0004_gallery_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
    ]
